import { NormalObject } from '../types';
export declare const encodeRegexpChars: (chars: string) => string;
export declare const typeOf: (target: any) => string;
export declare const isFn: (target: any) => boolean;
export declare const map: (target: string | any[] | NormalObject, fn: (item: any, index: string | number) => void) => NormalObject;
export declare const deepLoop: (obj: any, fn: (key: string | number, value: any, parent: object, path: string) => any, curPath?: string[]) => void;
export declare const makeRandom: (min: number, max: number) => number;
export declare const makeStrRangeList: (first?: string, last?: string, ...args: string[]) => string[];
export declare const isOptional: () => boolean;
export declare const capitalize: (target: string) => string;
export declare const decodeTrans: (target: string) => string;
export declare const getExp: (exp: string) => any;
export declare const range: (start: number, end: number, step?: number) => any;
export declare const deepCopy: (target: any, ...args: any[]) => any;
