language: node_js
before_install:
  - curl --silent --location https://rpm.nodesource.com/setup_12.x | sudo bash -
  - curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
  - sudo yum install yarn
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: 
  yarn: true
  directories:
    - node_modules
os:
  - "linux"
node_js:
  - "12"
script:
  - "npm test"
after_script:
  - "npm run coverage"
